---
title: "Biostatistics Project"
author: "杜昊雨"
date: "2023-01-12"
output: html_document
---

```{r }
library(readxl)
col<-c(1:105)
data <- read_xlsx("E:/大三上/生物统计方法/大作业/ace_NA.xlsx",sheet = 1)
name<-read_xlsx("E:/大三上/生物统计方法/大作业/mmc2.xlsx",sheet = 2)
name
data
```

```{r}
data=data.frame(data)
x<-dim(data)[1]
y<-dim(data)[2]
for (i in 1:x){
  high<-c()
  low<-c()
  for(j in 2:105){
    if(data[i,j]!=10){
    if(name[2,j]=="No" ){
      if(name[1,j]=="CNV_high"){
        high<-append(high,2^data[i,j])
      }
      else if(name[1,j]=="CNV_low"){
        low<-append(low,2^data[i,j])
      }
    }
    
    }
  }
  data[i,106]=mean(low)
  data[i,107]=mean(high)
  if(length(low)>1&length(high)>1){
    data[i,109]=wilcox.test(low, high, paired=F,
                            exact = F)$p.value
    
  }
  else{
    data[i,109]=-1
  }
}

```



```{r}
head(pro)
m<-length(pro)
-log10(pro[1])
write.csv(pro,file = "E:/project/1255.csv")
```


```{r}

library(readr)
finalresult <- read_csv("E:/project/1255.csv")

```


```{r}
finalresult=data.frame(finalresult)
x<-dim(finalresult)[1]
for(i in 1:x){
    finalresult[i,2]= log2(low[i]/high[i])
}
which.max(finalresult[,2])
finalresult
na_pro[4091]
```

```{r}
finalresult
x<-dim(finalresult)[1]
x
up=0
down=0
target<-c()
for(i in 1:x){
  if(finalresult[i,3]>1&finalresult[i,2]>0.5){
    target[i]="Upregulated"
    up=up+1
  }
  else if(finalresult[i,3]>1&finalresult[i,2]< -0.5){
    target[i]="Downregulated"
    down=down+1
  }
  else{
    target[i]="Not Significant"
  }
}
head(target)
```


```{r}
cbind(finalresult,target)
finalresult[2432,]
```
```{r}
library(ggplot2)
p1<-ggplot(finalresult,aes(x,p,color=target))+
  scale_color_manual(values=c("#105BA2","#CCCCCC","#FFB600FF"))+
  theme_bw()+
  theme(axis.text.x = element_text(angle=0,hjust=0.5,size=9,color="black",face="bold"))+
  theme(axis.title.x = element_text(angle=0,size=9,color="black"))+
  theme(plot.title = element_text(color = "black", size =12, hjust = 0.5))+
  labs(title=" Histone Acetylation Sites",y="-lg(p.adjusted)",x="log2(FC) CNV-low VS CNV-high")+
  geom_jitter(width = 0.1)+
geom_hline(aes(yintercept = 1),linetype="dashed",width=0.1)+
  geom_vline(aes(xintercept =-0.5),linetype="dashed",width=0.1)+
  geom_vline(aes(
    xintercept = 0.5),linetype="dashed",width=0.1)+
  scale_x_continuous(breaks = seq(-2, 2, by = 0.5))
p1
```


```{r}
up
down
```



```{r}
library(readxl)
col<-c(1:105)
data <- read_xlsx("E:/大三上/生物统计方法/大作业/ace_NA.xlsx",sheet = 1)
name<-read_xlsx("E:/大三上/生物统计方法/大作业/mmc2.xlsx",sheet = 2)
name
data
```

```{r}
#create data frame with 0 rows and 3 columns
new_data <- data.frame(matrix(ncol = 104, nrow = 0))
#provide column names
head(new_data)
```


```{r}
data=data.frame(data)
new_name<-c()
x<-dim(data)[1]
y<-dim(data)[2]
a=1
for (i in 1:(x)){
  flag=0
  for(j in 2:105){
    if(data[i,j]==10){
      flag=1
      break
      }
  }
  if(flag==0){
    for(m in 2:105)
    {
      new_data[a,m-1]<-data[i,m]
      
    }
    new_name<-append(new_name,data[i,1])
    a=a+1
  }
  
 
}

```

```{r}
new_data
library(dplyr)
```


```{r}
colnames(new_data) <- colnames(name)
```

```{r}
library(readxl)
pearson <- read_excel("D:/美赛/数据/pearson.xlsx")
pearson
```



```{r}
gc()
library(pheatmap)
pheatmap(pearson,color =  colorRampPalette(c("#00BBFF", "white", "#FF0000"))(10),show_rownames=FALSE,cutree_rows=TRUE,fontsize_col=5,scale = "row",cluster_cols = FALSE,cluster_rows = FALSE,border=FALSE,main = "Acetylproteomics site level data in Tumor")
```



```{r}
library(readxl)
CNV_data <- read_excel("E:/大三上/生物统计方法/大作业/NIHMS1566438-supplement-2.xlsx",sheet=7)
head(CNV_data)
```

```{r}
library(pheatmap)
x<-dim(new_data)[1]
y<-dim(new_data)[2]
for (i in 1:x){
  flag=0
  for(j in 2:y){
   new_data[i,j]=round(new_data[i,j],4)
  
    
 
  }
}
pheatmap(new_data,cluster_cols = FALSE)
colnames(new_data) <- colnames(name)
```



```{r}
library(readxl)
CNV <- read_excel("E:/大三上/生物统计方法/大作业/CNV.xlsx")

```

```{r}
# 加载R包，没有安装请先安装  install.packages("包名") 
library(ggplot2)
library(reshape2)


CNV = melt(CNV)                    # melt出自reshape2包
head(CNV)                         # 查看转换完成的数据的前几行
#   X         variable   value
# 1 Pathway1       Up    35
# 2 Pathway2       Up    27
# 3 Pathway3       Up    58
# 4 Pathway4       Up    24
# 5 Pathway5       Up     4
# 6 Pathway6       Up    58

# 绘图
ggplot(CNV, aes(
                x = factor(idx,levels = unique(idx)),             # 将第一列转化为因子，目的是显示顺序与文件顺序相同，否则按照字母顺序排序
                y = ifelse(variable == "CNV_AMP", value, -value),  # 判断分组情况，将两个柱子画在0的两侧
                fill = variable)) +
  geom_bar(stat = 'identity')+                                # 画柱形图
  coord_flip()+                                               # x轴与y轴互换位置

  scale_y_continuous(                                         # 调整y轴
    labels = abs,                                             # 刻度设置为绝对值
    expand = expansion(mult = c(0.1, 0.1)))  +
  labs(title=" CNV of Genomic Subtype",x="idx",y="Copy Number ")+
  theme_bw()+
  theme(axis.text.x = element_text(angle=0,hjust=0.5,size=9,color="black",face="bold"),axis.text.y = element_text(angle=0,hjust=0.5,size=3,color="black"))+
  theme(axis.title.x = element_text(angle=0,size=9,color="black"))+
  theme(plot.title = element_text(color = "black", size =12, hjust = 0.5))
  
  # 在y轴的两侧，留下一部分的空白位置，防止加标签的时候，显示不全
```








